### ISSUE TITLE
Allow WordPress.org to push SVN theme/plugin changes to Tide services

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#82] opened 2018-05-21 19:25 UTC

**Comment by jeffpaul** [comment] 2018-08-22 02:42
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882735000100) today, we're tagging this to the `1.0.0` release

**Comment by valendesigns** [comment] 2018-11-22 07:09
This is a duplicate of #91, which is now closed.

**Closed as completed by valendesigns** 2018-11-22 07:09 UTC
Labels: enhancement
