### ISSUE TITLE
Error when using authenticated request to get detailed report

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#151] opened 2018-09-19 23:01 UTC
@rheinardkorf commented on [Mon Jul 23 2018](https://github.com/wptide/tide-issues/issues/10)

Fetching a detailed report such as https://wptide.local/api/tide/v1/report/1234/raw/phpcs_phpcompatibility produces an error despite being an authenticated request and resource being available in bucket.

```
{
    "code": "report_fetch_error",
    "message": "Fetching report failed",
    "data": {
        "status": 500
    }
}
```

---

@valendesigns commented on [Thu Aug 09 2018](https://github.com/wptide/tide-issues/issues/10#issuecomment-411942513)

I can confirm that I'm seeing the same response even though authenticated.

---

@jeffpaul commented on [Tue Aug 28 2018](https://github.com/wptide/tide-issues/issues/10#issuecomment-416808944)

Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535489232000100) today, we're keeping this in the `1.0.0` release.  This is only happening in production, locally it's all working.  @valendesigns to finish fixing the build process then redeploy and test.

**Comment by jeffpaul** [comment] 2018-11-28 19:57
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543353919113600).

**Comment by valendesigns** [comment] 2019-03-01 13:00
This is now fixed and deployed. Basically the issue is that the `GOOGLE_APPLICATION_CREDENTIALS` environment variable was not set correctly on Google App Engine. So I worked out a way to add credentials with the deploy. However, this means that the solution is likely only temporary until I find a fix where the App Engine instances use their own credentials like their supposed to. Resolved for now.

**Closed as completed by valendesigns** 2019-03-01 13:00 UTC
Labels: bug
