### ISSUE TITLE
Higher value for SYNC_POOL_WORKERS causes errors in Sync Server

### ISSUE THREAD

**Issue by danlouw** [wptide/wptide#29] opened 2018-03-08 06:17 UTC
Steps to reproduce:

- Run the Sync Server locally with a value of `SYNC_POOL_WORKERS=250` in `.env` (the default value in `.env.dist`)

Result:

Usually the server is able to reach this point:
```
sync-server_1        | 2018/03/08 04:49:33 themes sync finished at 2018-03-08T04:49:33Z
```
But then starts getting errors like:

```
sync-server_1        | 2018/03/08 04:51:56 WP Migrate RequestError: send request failed
sync-server_1        | caused by: Post https://sqs.us-west-2.amazonaws.com/: dial tcp: lookup sqs.us-west-2.amazonaws.com on 192.168.65.1:53: no such host
```

I've tried lowering the value for `SYNC_POOL_WORKERS` from 250 to 125, then to 50, then to 25.

I got errors for all values except 25, although there's probably a point somewhere between 25 and 50 that should work. Still much lower than 250 though.

**Comment by rheinardkorf** [comment] 2018-03-08 22:59
We need to take into account resource usage, but the first issue to resolve this would be to create an SQS client pool.  Currently we have 1 client serving all the requests. It would be better to let several clients distribute the load and hopefully mitigate connection errors.

**Comment by jeffpaul** [comment] 2018-08-22 02:28
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882084000200) today, we're moving this to `Future Release`

**Comment by valendesigns** [comment] 2019-02-27 10:29
I cannot reproduce. Closing for now.

**Closed as completed by valendesigns** 2019-02-27 10:29 UTC
Labels: bug
